Feature/proximity
swzwij/Examen-Project pull request #29
Opened 2024-04-26 20:40 UTC by BNS-MarkUlrich

2024-05-06 09:26 UTC, swzwij requested changes

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityAgent.cs
> +#endregion
Are the testing regions still needed?

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityManager.cs
> +        private static readonly Dictionary<AgentTypes, List<ProximityAgent>> _proximityAgentsByType = new(); // Test later
"Test later" ?

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityAgent.cs
> +        public HashSet<ProximityAgent> RequestProximityData(float range = 0, params AgentTypes[] agentTypesToCheck)
Missing summary :)

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityManager.cs
> +        public static void Subscribe(this ProximityAgent agent, AgentTypes agentType)
Missing summary :)

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityManager.cs
> +        public static void Unsubscribe(this ProximityAgent agent)
Missing summary :)

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityManager.cs
> +        public static HashSet<ProximityAgent> GetAgentsOfType(AgentTypes agentTypes)
Missing summary :)

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityManager.cs
> +        public static HashSet<ProximityAgent> GetAgentsInRange(this ProximityAgent sourceAgent, float range, params AgentTypes[] agentTypes)
Missing summary :)

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/TestingProximity.cs
> +        //[SerializeField] private float _range = 15f;
Remove comments

2024-05-06 09:26 UTC, swzwij commented on Assets/Scripts/Proximity/TestingProximity.cs
> +                //_nearbyAgents = _proximityAgent.RequestProximityData(_range, _agentTypesToCheck).ToArray();
Remove comments

2024-05-06 20:12 UTC, BNS-MarkUlrich commented on Assets/Scripts/Proximity/ProximityManager.cs
> +        private static readonly Dictionary<AgentTypes, List<ProximityAgent>> _proximityAgentsByType = new(); // Test later
Shush

2024-05-07 07:49 UTC, swzwij requested changes

2024-05-07 07:49 UTC, swzwij commented on Assets/Scripts/Proximity/ProximityManager.cs
> +            foreach (var entity in _proximityAgents)
ew var

2024-05-07 08:24 UTC, swzwij approved these changes

2024-05-07 08:26 UTC, merged