feature/input
swzwij/Examen-Project pull request #3
Opened 2024-03-21 16:19 UTC by BNS-MarkUlrich

2024-03-22 09:21 UTC, swzwij requested changes

2024-03-22 09:21 UTC, swzwij commented on Assets/Scripts/Player/Interactor.cs
> +    [RequireComponent(typeof(Pointer))]
Is it needed for the interactor class to be depended on the pointer? shouldn't it be the other way around?

2024-03-22 09:21 UTC, swzwij commented on Assets/Scripts/Player/Interactor.cs
> +        {
Pull from develop and do a IsOwner check so only the owner of this player can do this interaction

2024-03-22 09:28 UTC, BNS-MarkUlrich commented on Assets/Scripts/Player/Interactor.cs
> +    [RequireComponent(typeof(Pointer))]
Would you point at what you interact with or interact with what you point at?

2024-03-22 10:34 UTC, BNS-MarkUlrich commented on Assets/Scripts/Player/Interactor.cs
> +    [RequireComponent(typeof(Pointer))]
I would say the interactor is dependant on the pointer, as you can't interact with something without "clicking" (pointing) at it first. I've slightly refactored the code to better reflect this. Let me know what you think.

2024-03-25 08:42 UTC, swzwij approved these changes

2024-03-25 08:42 UTC, merged