Feature/boss manager
swzwij/Examen-Project pull request #31
Opened 2024-05-13 11:39 UTC by Minoord

2024-05-16 07:58 UTC, swzwij requested changes

2024-05-16 07:58 UTC, swzwij commented on Assets/Art/Textures/UI/Healthbar/Base-no_skulls.png
T_BaseNoSkulls

2024-05-16 07:58 UTC, swzwij commented on Assets/Art/Textures/UI/Healthbar/Skulls.png
T_Skulls

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +        public Pathfinder MyPathFinder { set { p_pathfinder = value; } }
Can this be renamed to just `PathFinder` ?

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/PoolSystem/PoolSystem.cs
> +            else*/
Please remove commented code

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawnPoints.cs
> +public class EnemySpawnPoints : MonoBehaviour
Missing namespace

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawnPoints.cs
> +    public Transform Spawnpoint {  get { return _spawnpoint; } }
```suggestion
    public Transform Spawnpoint => _spawnpoint;
```

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawnPoints.cs
> +    public List<Transform> Waypoints {  get { return _waypoints; } }
```suggestion
    public List<Transform> Waypoints => _waypoints;
```

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +        [SerializeField] private int _enemyDownTimer = 60;
Please rename to either interval, or cooldown

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +        public void DespawnEnemy(EnemyHealthBar enemyHealthBar)
Missing summary

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawnPoints.cs
> +    public void SetWaypoints()
Missing summary

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +        private void SendEnemyInfoOnConnection(NetworkObject obj) => ReceiveEnemyInfoOnConnection(_enemiesHealth);
Please fully spell out parameter names

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +                sliders.Key.ClientInitialize(sliders.Value);
```suggestion
            foreach (EnemyHealthBar slider in currentActiveEnemySliders.Keys)
                slider.ClientInitialize(sliders.Value);
```

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +            GameObject enemy = PoolSystem.Instance.SpawnObject(_enemyPrefabs[randomEnemyPrefabNumber].name, _enemyPrefabs[randomEnemyPrefabNumber].gameObject);
Line exceeds the 120 character limit

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +            yield return new WaitForSeconds(0.33f);
Does this need to be hard coded in? if so either use a variable or a constant

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +        private void ReceiveEnemyInfoOnSpawn(EnemyHealthBar healthbar, float healthAmount) => healthbar.ClientInitialize(healthAmount);
Line exceeds the 120 character limit

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +                PoolSystem.Instance.DespawnObject(slider.Key.name, slider.Key.gameObject);
Same as the other for each loop comment

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/UI/EnemyHealthBar.cs
> +        [SerializeField] private bool _damage;
Remove

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/UI/EnemyHealthBar.cs
> +        public Slider HealthSlider => _healthBar;
```suggestion
        public Slider HealthBar => _healthBar;
```
please keep the variable names the same

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/UI/EnemyHealthBar.cs
> +            if (_damage) EnemyHealthData.TakeDamage(1);
```suggestion
            if (_damage) 
                EnemyHealthData.TakeDamage(1);
```

2024-05-16 07:58 UTC, swzwij commented on Assets/Scripts/Pathfinding/WaypointFollower.cs
> +        public void ResetWaypointIndex()
Missing summary

2024-05-17 13:16 UTC, Minoord commented on Assets/Scripts/Spawning/BossSpawning/EnemySpawner.cs
> +                sliders.Key.ClientInitialize(sliders.Value);
I can't do this, because I both need the key and value

2024-05-20 11:17 UTC, swzwij approved these changes

2024-05-20 11:20 UTC, merged