Feature/inventory UI
swzwij/Examen-Project pull request #32
Opened 2024-05-14 09:39 UTC by swzwij

2024-05-14 13:00 UTC, Minoord requested changes
When I try to test it, I couldn't place any towers and I saw that the exp bar wasn't in the correct position yet.  Now is this feature called inventory UI so if you don't do it here I understand that, but just a friendy reminder :)

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplay.cs
> +        }
I assume you did this because otherwise the line would be too long, but you can make it like this:
```suggestion
        private void OnEnable() 
        => InventorySystem.Instance.OnItemsChanged += UpdateDisplay;
```
or this:
```suggestion
        private void OnEnable() =>
           InventorySystem.Instance.OnItemsChanged += UpdateDisplay;
```

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplay.cs
> +            InventorySystem.Instance.OnItemsChanged -= UpdateDisplay;
Same thing as above

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplay.cs
> +            UpdateDisplay(_currentPackage);
Same things as above

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplay.cs
> +        public void UpdateDisplay()
Dont forget the summary

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Items/building/Building UI/StructureSelectButton.cs
> +        }
Why did you change this? if you dont like how long that line is, still just revert it because I will change that in my future PR

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Items/building/Building UI/StructureSelectButton.cs
> +        [SerializeField] private BuildMenu _buildMenu;
why did you add this?

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplayItem.cs
> +        public void Initialize(string item, int amount)
missing summary

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplayItem.cs
> +        public void UpdateItem(int amount)
missing summary

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/ServerInventory.cs
> +        if (!_inventorySystems[connection.ClientId].ContainsKey(new(newItem.Name)))
I find this a bit cursed that we keep creating new items here, can we maybe just changes this dictionary to a string?

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/ServerInventory.cs
> +        //     return;
if this isn't needed that remove it

2024-05-14 13:00 UTC, Minoord commented on Assets/Scripts/Player/Inventory/ServerInventory.cs
> +    [ServerRpc(RunLocally = true)]
what does this do?

2024-05-16 08:34 UTC, swzwij commented on Assets/Scripts/Player/Inventory/ServerInventory.cs
> +    [ServerRpc(RunLocally = true)]
True to also run the RPC logic locally.

2024-05-16 08:39 UTC, RyanDefost commented on Assets/Scripts/Items/building/Building UI/BuildMenuToggle.cs
> +        }
probably needs a summary

2024-05-16 08:39 UTC, RyanDefost commented on Assets/Scripts/Items/building/Building UI/BuildMenu.cs
> +        }
summary

2024-05-16 08:39 UTC, RyanDefost commented on Assets/Scripts/Items/InventoryPackage.cs
> +        }
summary

2024-05-16 08:52 UTC, Minoord requested changes

2024-05-16 08:52 UTC, Minoord commented on Assets/Scripts/Items/InventoryPackage.cs
> +        }
```suggestion
        public InventoryPackage(Dictionary<ItemInstance, int> items) =>  _items = items;
```

2024-05-16 08:52 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplayItem.cs
> +            _text.text = $"{amount}";
```suggestion
        public void UpdateItem(int amount) => _text.text = $"{amount}";
```

2024-05-16 11:15 UTC, Minoord requested changes

2024-05-16 11:15 UTC, Minoord commented on Assets/Scripts/Items/InventoryPackage.cs
> +        /// <param name="items">The InventoryPackages</param>
Please add a period to the end of this sentence

2024-05-16 11:15 UTC, Minoord commented on Assets/Scripts/Items/building/Building UI/BuildMenuToggle.cs
> +        }
Samuel dont resolve it before you push

2024-05-16 11:15 UTC, Minoord commented on Assets/Scripts/Player/Inventory/InventoryDisplay.cs
> +        /// <summary>
```suggestion
        private void OnDisable() => InventorySystem.Instance.OnItemsChanged -= UpdateDisplay;

        /// <summary>
```

2024-05-16 11:20 UTC, Minoord reviewed
When I want to place a tower it keep spawning at the same point in the map, I can't drag it to the place I want it to be. 

The rest looks good

2024-05-16 13:18 UTC, Minoord requested changes
last code points

2024-05-16 13:18 UTC, Minoord commented on Assets/Scripts/Items/building/Building UI/BuildMenu.cs
> +        /// <param name="isActive">Whether the build menu should activate</param>
Let this end on a period

2024-05-16 13:18 UTC, Minoord commented on Assets/Scripts/Items/building/Building UI/BuildMenuToggle.cs
> +        /// <param name="isActive">Whether the build menu should activate</param>
Let this end on a period

2024-05-17 07:55 UTC, Minoord requested changes
Samuel I realised something, you only have 1 building right now. we are missing the wall and the road. I am okay with approving this without them, but then I would appreciate that you can added them later in a different PR. Also do we have UI if you aren't high enough level to unlock buildings?

2024-05-17 07:59 UTC, Minoord approved these changes

2024-05-17 07:59 UTC, merged