Feature/boss area attack
swzwij/Examen-Project pull request #37
Opened 2024-05-16 08:31 UTC by BNS-MarkUlrich

2024-05-17 13:17 UTC, swzwij requested changes

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Animations/Boss/Boss_Controller.controller
Please use the correct prefix and CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Animations/Boss/Boss_Controller.controller.meta
Please use the correct prefix and CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Animations/Boss/SK_Boss_Export003.fbx
Please use CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Animations/Boss/SK_Boss_Export02.fbx
Please use CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Animations/Boss/SK_Boss_Export_Final.fbx
Please use CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Textures/Boss/DefaultMaterial_baseColor.png
Please use the correct prefix and CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Textures/Boss/DefaultMaterial_normal.png
Please use the correct prefix and CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Textures/Boss/DefaultMaterial_occlusionRoughnessMetallic.png
Please use the correct prefix and CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/Art/Textures/Projector/red-area-HD.png
Please use the correct prefix and CamelCase

2024-05-17 13:17 UTC, swzwij commented on Assets/PlayerMover.cs
> +public class PlayerMover : MonoBehaviour
Missing namespace

2024-05-17 13:17 UTC, swzwij commented on Assets/PlayerMover.cs
> +    private void StartMoving(GameObject attacker)
```suggestion
    [SerializeField] private float _rayDistance = 2f; 
    
    private void StartMoving(GameObject attacker)
```

2024-05-17 13:17 UTC, swzwij commented on Assets/PlayerMover.cs
> +    private void StartMoving(GameObject attacker)
Can be one liner

2024-05-17 13:17 UTC, swzwij commented on Assets/PlayerMover.cs
> +        var attackDiraction = attackPosition - startPoint.normalized;
Please use explicit type instead of var

2024-05-17 13:17 UTC, swzwij commented on Assets/Scripts/NPC/Boss.cs
> +        public override void Interact(NetworkConnection connection, float damageAmount = 0)
Can be a one liner

2024-05-17 13:17 UTC, swzwij commented on Assets/Scripts/NPC/Boss.cs
> +        public override void PlayInteractingSound()
Eather remove or add a `//TODO:`

2024-05-17 13:17 UTC, swzwij commented on Assets/Scripts/NPC/Boss.cs
> +        public override void Interact(NetworkConnection connection, float damageAmount = 0)
Missing summary

2024-05-17 13:17 UTC, swzwij commented on Assets/Scripts/NPC/Boss.cs
> +        public override void PlayInteractingSound()
Missing summary

2024-05-17 13:17 UTC, swzwij commented on Assets/Scripts/NPC/Boss.cs
> +        public virtual void BroadcastInteract()
Missing summary

2024-05-17 13:17 UTC, swzwij commented on Assets/Scripts/Pathfinding/WaypointFollower.cs
> +        public void ToggleWaiting(bool isWaiting)
Missing summary

2024-05-20 07:29 UTC, BNS-MarkUlrich commented on Assets/Art/Animations/Boss/Boss_Controller.controller
There are no prefix conventions for controllers

2024-05-20 11:19 UTC, swzwij approved these changes

2024-05-20 14:40 UTC, swzwij approved these changes

2024-05-20 14:41 UTC, merged