Feature/pathfinding
swzwij/Examen-Project pull request #8
Opened 2024-04-02 07:58 UTC by BNS-MarkUlrich

2024-04-02 08:05 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +        protected void OnDrawGizmos()
broadcast

2024-04-02 08:05 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +        protected void BroadcastPosition(Vector3 position)
where it get called?

2024-04-02 08:05 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +        protected IEnumerator FollowPath()
SERVER

2024-04-02 08:05 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +        public void StartPath(Vector3 target)
server

2024-04-03 09:53 UTC, swzwij requested changes

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +                    initializeElement(x, y);
```suggestion
            for (int x = 0; x < gridSize.x; x++)
            {
                for (int y = 0; y < gridSize.y; y++)
                    initializeElement(x, y);
            }
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +            if (IsWalkableArea(nodePosition, out float elevation))
invert if

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +                    cell.AddNode(_nodes[nodeX, nodeY]);
```suggestion
            for (int nodeX = startX; nodeX < endX; nodeX++)
            {
                for (int nodeY = startY; nodeY < endY; nodeY++)
                    cell.AddNode(_nodes[nodeX, nodeY]);
            }
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +                    CheckNodeConnections(x, y);
```suggestion
            foreach (int x in Enumerable.Range(0, _gridSize.x))
            {
                foreach (int y in Enumerable.Range(0, _gridSize.y))
                    CheckNodeConnections(x, y);
            }
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +            Gizmos.DrawWireCube(transform.position + new Vector3(_gridSize.x * _nodeDistance / 2f, _maxWorldHeight / 2, _gridSize.y * _nodeDistance / 2f), new Vector3(_gridSize.x * _nodeDistance, _ma
exceeds 120 chars

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +            if (_nodes != null)
invert if

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private Vector3 position;
```suggestion
        private Vector3 _position;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private List<Node> connectedNodes;
```suggestion
        private List<Node> _connectedNodes;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private float elevation;
```suggestion
        private float _elevation;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private float maxElevationDifference;
```suggestion
        private float _maxElevationDifference;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private float maxConnectionDistance;
```suggestion
        private float _maxConnectionDistance;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private bool isWalkable;
```suggestion
        private bool _isWalkable;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private Vector2Int gridPosition;
```suggestion
        private Vector2Int _gridPosition;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private Node parent;
```suggestion
        private Node _parent;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private int gCost; // Movement cost
add `_` prefix and use a proper name instead of a 'g' prefix

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        private int hCost; // Heuristic cost
add `_` prefix and use a proper name instead of a 'h' prefix

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        public int FCost { get { return gCost + hCost; } } // Total cost
Same here

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        public Node(Vector3 pos)
```suggestion
        public Node(Vector3 position)
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +            if (CalculateElevation(node) <= maxElevationDifference && CalculateDistance(node) <= maxConnectionDistance)
invert if

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +        public event Action OnPathCompleted;
```suggestion
        public bool IsPathBlocked 
            => Physics.Raycast(transform.position, transform.forward, p_obstacleCheckDistance, p_obstaclesLayerMask);
        
        public event Action OnPathCompleted;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +            if (IsPathBlocked && !p_hasFoundBlockage)
invert if

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/PathFollower.cs
> +            if (p_pointer != null)
inver if

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +            HashSet<Node> closedSet = new();
Move these to variables and clear them when this function gets called. This generates less garbage

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +        public List<Node> FindPath(Vector3 startPos, Vector3 targetPos)
Would it be possible to part this method into multiple because currently it is almost 50 lines long

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +        public List<Node> FindPath(Vector3 startPos, Vector3 targetPos)
```suggestion
        public List<Node> FindPath(Vector3 startPosition, Vector3 targetPosition)
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +        private int CalculateDistance(Node a, Node b)
```suggestion
        private int CalculateDistance(Node nodeA, Node nodeB)
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Player/Interactor.cs
> +        //private void OnDisable() => _pointer.OnPointedAtPosition -= DebugPointer;
Remove comments

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +        private bool _isInitialized;
```suggestion
        [SerializeField] private int _maxNodeConnections = 3;
        
        private Node[,] _nodes;
        private Cell[,] _cells;
        private bool _isInitialized;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +        [SerializeField] Vector2Int _gridSize;
```suggestion
        [SerializeField] private Vector2Int _gridSize;
```

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +            if (!_isInitialized)
invert if

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +            List<Node> path = new List<Node>();
Make it a variable and clear it to decrease the garbage collection

2024-04-03 09:53 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +                foreach (Node neighbor in currentNode.ConnectedNodes)
```suggestion
                foreach (Node neighbour in currentNode.ConnectedNodes)
```

2024-04-04 08:08 UTC, swzwij requested changes

2024-04-04 08:08 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +        private void OnDrawGizmos() // Mark Todo: Clean up this method. Move drawing to owner classes.
Still todo?

2024-04-04 08:08 UTC, swzwij commented on Assets/Scripts/Pathfinding/Grid/Node.cs
> +        public int FinalCost { get { return _goalCost + _heuristicCost; } }
```suggestion
        public int FinalCost => return _goalCost + _heuristicCost;
```

2024-04-04 08:08 UTC, swzwij commented on Assets/Scripts/Pathfinding/Pathfinder.cs
> +                }
Exceeds 120 char limit, and doesn't need brackets

2024-04-04 08:52 UTC, BNS-MarkUlrich commented on Assets/Scripts/Pathfinding/Grid/GridSystem.cs
> +        private void OnDrawGizmos() // Mark Todo: Clean up this method. Move drawing to owner classes.
Nah it's fine here as far as I'm concerned.

2024-04-04 08:56 UTC, swzwij approved these changes

2024-04-04 08:57 UTC, merged